### ISSUE TITLE
Caused Atmosphere 0.19.1 to freeze at Nintendo Switch logo on reboot, post-install

### ISSUE THREAD

**Issue by RyokoAsakura** [plutooo/nx-btred#1]
System is unpatched original Switch, FW 12.0.1, Atmosphere 0.19.1, EmuMMC.

Installed nx-btred 0.9 via FTP, already had latest Mission Control installed.

Attempted pairing with Crusher ANC bluetooth headphones, pairing was successful, but upon exiting app and homebrew menu, no sound was transmitted to the headphones. Went into homebrew menu and used Reboot to Payload to reboot system.

Upon reboot, system hung at Nintendo Switch logo. I then executed a hard power down using a long press of the power button. Attempted cold boot with jig using TegraRCMGUI with the latest fusee-primary. System began boot process and again hung at the Nintendo Switch logo.

I physically removed the SD card and mounted it in Windows 10. I manually deleted both the /atmosphere/contents/0100000000000081 folder and the /switch/btpair.nro file from the SD card.

I then replaced the SD card and attempted another cold boot with jig using TegraRCMGUI with the latest fusee-primary. System began boot process and this time booted just fine.

**Comment by vaugerbird** [comment]
Same exact issue here. I added the files through Hekate UMS mode, and the boot process stalls at the Nintendo Switch logo. After removing the files for nx-btred, the switch boots fine. If it helps at all, I am on 12.0.0, Atmosphere 0.19.1, and EmuMMC.

**Comment by JonJaded** [comment]
Dealing with the same issue, I just scanned my atmosphere folder and I found a total of 3 boot2.flag[s] and the three belong to:

MissionControl
nx-btred
tesla-overlay

Which makes me feel it isn't a sys-module memory issue. I installed via Hekate UMS mode as well.

Edit: I did launch the nro before MissionControl was on, showed me a screen about a device. After enabling and restarting, came the issue.

**Comment by plutooo** [comment]
Managed to repro -- fix out soon

**Comment by plutooo** [comment]
Pushed version 0.9.1 -- can you confirm fixed?

**Comment by JonJaded** [comment]
> Pushed version 0.9.1 -- can you confirm fixed?

Boots and launches perfectly now! Was able to instantly connect my bluetooth device. Nice quick fix, thanks.

**Comment by plutooo** [comment]
Awesome, thanks. Fixed in 0.9.1.

**Comment by RyokoAsakura** [comment]
Finally got around to loading nx-btred 0.9.3 and can confirm (unnecessarily) that it now works as expected. Thank you, @plutooo!
