### ISSUE TITLE
Very loud audio

### ISSUE THREAD

**Issue by Yot360** [plutooo/nx-btred#11]
Hey, I wanted to try nx-btred, my BT jbl headset connected but when I started a game my ears broke lmao, so I went back to home menu, and restarted the game with volume at the lowest, I could now hear the sound but it’s still very loud.
It’ll be nice if there was a sound control directly in the app on HB menu or like an overlay with Tesla menu.
Great work, even if it’s not perfect it works!

**Comment by impeeza** [comment]
Did you read the instructions? it states: 


⚠️ Warning ⚠️

YOU USE THIS AT YOUR OWN RISK. Not every headphone brand has been tested. There may be really loud noise. Be careful, start out with a low volume, and then increase, if you like. In case of any type of malfunction, the sound will stop immediately if you hit the power button.

is clear you are advised to start with lowest volume and set the level you want.

**Comment by Yot360** [comment]
> Did you read the instructions? it states: 
> 
> 
> 
> 
> 
> ⚠️ Warning ⚠️
> 
> 
> 
> YOU USE THIS AT YOUR OWN RISK. Not every headphone brand has been tested. There may be really loud noise. Be careful, start out with a low volume, and then increase, if you like. In case of any type of malfunction, the sound will stop immediately if you hit the power button.
> 
> 
> 
> is clear you are advised to start with lowest volume and set the level you want.

Yes I did, I just didn't think it would be that loud.

**Comment by 3DSBricker** [comment]
For me with my Bluetooth to 3.5mm its really low volume, luckily I use an amplifier with that. My Sony headphone doesn't output audio at all. No noise, no audio, nothing.

**Comment by evertonstz** [comment]
> 
> 
> Did you read the instructions? it states:
> 
> ⚠️ Warning ⚠️
> 
> YOU USE THIS AT YOUR OWN RISK. Not every headphone brand has been tested. There may be really loud noise. Be careful, start out with a low volume, and then increase, if you like. In case of any type of malfunction, the sound will stop immediately if you hit the power button.
> 
> is clear you are advised to start with lowest volume and set the level you want.

Well, if his sin is not reading the readme, yours is not reading his post.

Anyways, OP, the problem seems to be audio from the console and the headphones are "decoupled", that means there are two places you can change volume in current version: in the Switch and in the Headphone itself.
You're probably changing audio in the Switch, that's why it's loud, try leaving the slider in the switch in the minimum and after that, change the audio using your BT Headphone audio keys. If they don't actually have keys/gesture control for audio that would be a problem, I would advise uninstalling and wait for the homebrew to mature and couple console and headphone audio together.

**Comment by Yot360** [comment]
> > 
> 
> > 
> 
> > Did you read the instructions? it states:
> 
> > 
> 
> > ⚠️ Warning ⚠️
> 
> > 
> 
> > YOU USE THIS AT YOUR OWN RISK. Not every headphone brand has been tested. There may be really loud noise. Be careful, start out with a low volume, and then increase, if you like. In case of any type of malfunction, the sound will stop immediately if you hit the power button.
> 
> > 
> 
> > is clear you are advised to start with lowest volume and set the level you want.
> 
> 
> 
> Well, if his sin is not reading the readme, yours is not reading his post.
> 
> 
> 
> Anyways, OP, the problem seems to be audio from the console and the headphones are "decoupled", that means there are two places you can change volume in current version: in the Switch and in the Headphone itself.
> 
> You're probably changing audio in the Switch, that's why it's loud, try leaving the slider in the switch in the minimum and after that, change the audio using your BT Headphone audio keys. If they don't actually have keys/gesture control for audio that would be a problem, I would advise uninstalling and wait for the homebrew to mature and couple console and headphone audio together.

Oh, totally forgot I could use the buttons on my headphone... Thanks I will try that!

**Comment by Yot360** [comment]
> > 
> 
> > 
> 
> > Did you read the instructions? it states:
> 
> > 
> 
> > ⚠️ Warning ⚠️
> 
> > 
> 
> > YOU USE THIS AT YOUR OWN RISK. Not every headphone brand has been tested. There may be really loud noise. Be careful, start out with a low volume, and then increase, if you like. In case of any type of malfunction, the sound will stop immediately if you hit the power button.
> 
> > 
> 
> > is clear you are advised to start with lowest volume and set the level you want.
> 
> 
> 
> Well, if his sin is not reading the readme, yours is not reading his post.
> 
> 
> 
> Anyways, OP, the problem seems to be audio from the console and the headphones are "decoupled", that means there are two places you can change volume in current version: in the Switch and in the Headphone itself.
> 
> You're probably changing audio in the Switch, that's why it's loud, try leaving the slider in the switch in the minimum and after that, change the audio using your BT Headphone audio keys. If they don't actually have keys/gesture control for audio that would be a problem, I would advise uninstalling and wait for the homebrew to mature and couple console and headphone audio together.

This fixed it! Thank you
