### ISSUE TITLE
Can not compile btpair

### ISSUE THREAD

**Issue by lunixoid** [plutooo/nx-btred#14]
Hi, I would like to contribute to your awesome project. But I can not compile btpair (btred is good now), with followed issues:

- `nx-btred/btpair/source/bt_pairing_manager.cpp:143:49: error: cannot convert 'BtdrvEventType*' to 'u32*' {aka 'unsigned int*'}`
- nx-btred/btpair/source/bt_pairing_manager.cpp:154:38: error: 'struct BtdrvEventInfo::<unnamed union>::<unnamed>' has no member named 'v12'
- `ssp_request` has no 'v12' field also and so on

Build environment:
latest docker image devkitpro/devkita64
latest build from repo https://github.com/ndeadly/libnx/tree/master (marked as git-submodule in MissionControl, so I build master's HEAD of this repo)

$ /opt/devkitpro/devkitA64/bin/aarch64-none-elf-gcc --version
aarch64-none-elf-gcc (devkitA64 release 16) 10.2.0

**Comment by 3DSBricker** [comment]
I asked it before and he explained it. https://github.com/plutooo/nx-btred/issues/6
