### ISSUE TITLE
nx-btred turns off device once it enters sleep mode

### ISSUE THREAD

**Issue by JonJaded** [plutooo/nx-btred#22]
**Configuration**
AMS M.19.2
FW 12.0.1
MissionControl 0.5.0 pre-release 2
nx-btred 0.9.3
Headset Ghostek SoDrop 2.0

**Situation**

With my paired headphones (they work perfectly with nx-btred), any time it my switch goes into sleep mode, whether by forcing it via power button/home screen or by screen on timeout, the switch goes into an odd state where it's off, but still drains battery. It doesn't enter RCM mode, but pressing either the power button or volume buttons after, AMS does a fatal reboot, sending the reboot_payload and then booting back into Horizon OS.

I am nearly 99% sure that the switch enters AMS_fatal, but the screen is off so it doesn't get rendered; thus why the battery is drained so quickly in this mode. (This is the 2nd time I've woken up to the switch completely dead.)

By deleting my current _settings.bin_, I was able to remove the issue and enter sleep mode perfectly. But once I re-pair the headphones after, the same issue occurs. This happens even if the headphones are off and not paired during the time it is on.

I've attached the generated settings.bin causing issues.

[config.zip](https://github.com/plutooo/nx-btred/files/6418716/config.zip)

Thank you again for this amazing tool.

**Comment by JonJaded** [comment]
Dupe of #10

According to the dumps on SD, it's definetly an ams_fatal crash while entering sleep. Other than this problem, everything works perfectly with my headphones. Can go as loud or as quiet on both headphones and switch and theres "0 latency" on my pair.

**Comment by christorrella** [comment]
I think this is listed as a "safety feature" for just in case something goes wrong, this is in the README

**Comment by JonJaded** [comment]
We have official support now.
