### ISSUE TITLE
Initialize f601

### ISSUE THREAD

**Issue by dralien484** [plutooo/nx-btred#3]
When launching the pairing manager all I get is a black screen that says BtPairingManager Initialize f601. It is unresponsive to any button presses. Im on firmware 12.0.1 and latest version of atmosphere and mission control.

**Comment by plutooo** [comment]
This happens if MissionControl is outdated / not running. Please try reinstalling it. Make sure it is the pre-release version

**Comment by dralien484** [comment]
I tried reinstalling it, but still says the same thing. Not sure if mission control is working though since you can't pair controllers in the pre- release version. Do you need a paired controller for this to work?

**Comment by plutooo** [comment]
No paired controller is required. This error means MissionControl was not installed correctly; did you extract the files properly?

**Comment by dralien484** [comment]
I got it working. The flags (boot2.flag) for some reason were not copying over ftp. I plugged my sd card into my computer directly to copy the files and it works perfectly now. Thank you for the help and all your hard work.

**Comment by Jack-Taylor-Gorman** [comment]
Same issue, my problem was that I didn't see the 3 pre-release
https://github.com/ndeadly/MissionControl/releases/tag/v0.5.0-alpha.3
This is the most recent for anybody wondering, it's recompiled to work with atmosphere 0.19.3 on 12.0.2
