### ISSUE TITLE
doesn’t seem to be working

### ISSUE THREAD

**Issue by jozz024** [plutooo/nx-btred#4]
the headphones are connected,it just refuses to give me audio even in game. both the headphone volume and switch volume are 0<, so i don't know what the issue could be.

**Comment by plutooo** [comment]
I just pushed an update 0.9.2, please try it

**Comment by jozz024** [comment]
will do!

**Comment by jozz024** [comment]
it works! although as someone said in a different thread, it doesn't work with games that you can't record clips in.

**Comment by plutooo** [comment]
Can you give me an example of such a game?

**Comment by jozz024** [comment]
Super Smash Bros. Ultimate is one of the games that doesn't work if that is what you're asking.

**Comment by plutooo** [comment]
Okay, I'll look into it later. Fixed
