### ISSUE TITLE
Issue with another sysmodule

### ISSUE THREAD

**Issue by Jump-Bee** [plutooo/nx-btred#5]
i just want to inform you about some issue with sys-ftpd-light sysmodule,
after reboot and i try to access homebrew menu from album or tittle override, the device screen will stuck and i must force shutdown my device
disabling sys-ftpd-light via sysmodule.ovl make it work.
and thankyou for your work

**Comment by Jump-Bee** [comment]
i'm so sorry, i think its problem witch mission control sysmodule, not yours,
i try disabling mission control sysmodule, and sys-ftpd-work fine, there is no problem accesing homebrew menu via album or tittle override

**Comment by plutooo** [comment]
Thanks for clarifying
