### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by 3DSBricker** [plutooo/nx-btred#6]
Hello, sorry if this is not appropriate to send here but I just can't compile it. Make gives lots of errors, it first compiles bt_pairing_manager.cpp and gives these errors:

`matthijs@UbuROG:~/nx-btred$ make
make -C btpair
make[1]: Map '/home/matthijs/nx-btred/btpair' wordt binnengegaan
bt_pairing_manager.cpp
/home/matthijs/nx-btred/btpair/source/bt_pairing_manager.cpp: In member function 'void BtPairingManager::PollEvents()':
/home/matthijs/nx-btred/btpair/source/bt_pairing_manager.cpp:113:10: error: 'btdrvGetConnectedAudioDevice' was not declared in this scope
  113 |     rc = btdrvGetConnectedAudioDevice(audio_addrs, 8, &total_out);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/matthijs/nx-btred/btpair/source/bt_pairing_manager.cpp:143:49: error: cannot convert 'BtdrvEventType*' to 'u32*' {aka 'unsigned int*'}
  143 |     rc = btdrvGetEventInfo(&info, sizeof(info), &type);
      |                                                 ^~~~~
      |                                                 |
      |                                                 BtdrvEventType*
In file included from /opt/devkitpro/libnx/include/switch/services/bt.h:11,
                 from /opt/devkitpro/libnx/include/switch.h:98,
                 from /home/matthijs/nx-btred/btpair/source/bt_pairing_manager.cpp:3:
/opt/devkitpro/libnx/include/switch/services/../services/btdrv.h:359:58: note:   initializing argument 3 of 'Result btdrvGetEventInfo(void*, size_t, u32*)'
  359 | Result btdrvGetEventInfo(void* buffer, size_t size, u32 *type);
      |                                                     ~~~~~^~~~
/home/matthijs/nx-btred/btpair/source/bt_pairing_manager.cpp:154:38: error: 'struct BtdrvEventInfo::<unnamed union>::<unnamed>' has no member named 'v12'
  154 |         btaddr = info.inquiry_device.v12.addr;
      |                                      ^~~
/home/matthijs/nx-btred/btpair/source/bt_pairing_manager.cpp:160:60: error: 'struct BtdrvEventInfo::<unnamed union>::<unnamed>' has no member named 'v12'
  160 |         memcpy(m_devices[btaddr].name, info.inquiry_device.v12.name, sizeof(m_devices[btaddr].name));
      |                                                            ^~~
/home/matthijs/nx-btred/btpair/source/bt_pairing_manager.cpp:166:34: error: 'struct BtdrvEventInfo::<unnamed union>::<unnamed>' has no member named 'v12'
  166 |         if ((info.inquiry_status.v12.status & 0xff) == 0)
      |                                  ^~~
/home/matthijs/nx-btred/btpair/source/bt_pairing_manager.cpp:172:35: error: 'struct BtdrvEventInfo::<unnamed union>::<unnamed>' has no member named 'v12'
  172 |         btaddr = info.ssp_request.v12.addr;
      |                                   ^~~
/home/matthijs/nx-btred/btpair/source/bt_pairing_manager.cpp:179:58: error: 'struct BtdrvEventInfo::<unnamed union>::<unnamed>' has no member named 'v12'
  179 |         m_devices[btaddr].ssp_passkey = info.ssp_request.v12.passkey;
      |                                                          ^~~
/home/matthijs/nx-btred/btpair/source/bt_pairing_manager.cpp:182:80: error: 'struct BtdrvEventInfo::<unnamed union>::<unnamed>' has no member named 'v12'
  182 | drvRespondToSspRequestNew(btaddr, 0, true, info.ssp_request.v12.passkey);
      |                                                             ^~~

make[2]: *** [/opt/devkitpro/devkitA64/base_rules:14: bt_pairing_manager.o] Fout 1
make[1]: *** [Makefile:169: build] Fout 2
make[1]: Map '/home/matthijs/nx-btred/btpair' wordt verlaten
make: *** [Makefile:4: all] Fout 2`

The text is Dutch but the errors are English.
Also when going into the btred folder and doing make there gives many more errors:

`matthijs@UbuROG:~/nx-btred/btred$ make
bt_audio_device.cpp
In file included from /home/matthijs/nx-btred/btred/source/bt_audio_manager.h:5,
                 from /home/matthijs/nx-btred/btred/source/bt_audio_device.cpp:8:
/home/matthijs/nx-btred/btred/source/bt_audio_device.h:43:5: error: 'BtdrvAudioOutState' does not name a type; did you mean 'AudioOutState'?
   43 |     BtdrvAudioOutState m_btdrv_state;
      |     ^~~~~~~~~~~~~~~~~~
      |     AudioOutState
/home/matthijs/nx-btred/btred/source/bt_audio_device.cpp: In member function 'Result BtAudioDevice::InitializeBtdrv()':
/home/matthijs/nx-btred/btred/source/bt_audio_device.cpp:74:10: error: 'btdrvOpenAudioOut' was not declared in this scope; did you mean 'audoutOpenAudioOut'?
   74 |     rc = btdrvOpenAudioOut(m_addr, &m_btdrv_handle);
      |          ^~~~~~~~~~~~~~~~~
      |          audoutOpenAudioOut
/home/matthijs/nx-btred/btred/source/bt_audio_device.cpp:81:10: error: 'btdrvAcquireAudioOutStateChangedEvent' was not declared in this scope; did you mean 'btdevAcquireBleConnectionStateChangedEvent'?
   81 |     rc = btdrvAcquireAudioOutStateChangedEvent(m_btdrv_handle, &m_btdrv_statechange_event, true);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |          btdevAcquireBleConnectionStateChangedEvent
/home/matthijs/nx-btred/btred/source/bt_audio_device.cpp:84:9: error: 'btdrvCloseAudioOut' was not declared in this scope
   84 |         btdrvCloseAudioOut(m_btdrv_handle);
      |         ^~~~~~~~~~~~~~~~~~
/home/matthijs/nx-btred/btred/source/bt_audio_device.cpp:89:49: error: 'm_btdrv_state' was not declared in this scope
   89 |     rc = btdrvGetAudioOutState(m_btdrv_handle, &m_btdrv_state);
      |                                                 ^~~~~~~~~~~~~
/home/matthijs/nx-btred/btred/source/bt_audio_device.cpp:89:10: error: 'btdrvGetAudioOutState' was not declared in this scope; did you mean 'audoutGetAudioOutState'?
   89 |     rc = btdrvGetAudioOutState(m_btdrv_handle, &m_btdrv_state);
      |          ^~~~~~~~~~~~~~~~~~~~~
      |          audoutGetAudioOutState
/home/matthijs/nx-btred/btred/source/bt_audio_device.cpp:93:9: error: 'btdrvCloseAudioOut' was not declared in this scope
   93 |         btdrvCloseAudioOut(m_btdrv_handle);
      |         ^~~~~~~~~~~~~~~~~~
/home/matthijs/nx-btred/btred/source/bt_audio_device.cpp:98:5: error: 'BtdrvPcmParameter' was not declared in this scope
   98 |     BtdrvPcmParameter param;
      |     ^~~~~~~~~~~~~~~~~
/home/matthijs/nx-btred/btred/source/bt_audio_device.cpp:99:5: error: 'param' was not declared in this scope
   99 |     param.unk_x0 = 1;
      |     ^~~~~
/home/matthijs/nx-btred/btred/source/bt_audio_device.cpp:106:10: error: 'btdrvStartAudioOut' was not declared in this scope; did you mean 'audoutStartAudioOut'?
  106 |     rc = btdrvStartAudioOut(m_btdrv_handle, &param, latency, &latency, &out1);
      |          ^~~~~~~~~~~~~~~~~~
      |          audoutStartAudioOut
/home/matthijs/nx-btred/btred/source/bt_audio_device.cpp:115:9: error: 'btdrvCloseAudioOut' was not declared in this scope
  115 |         btdrvCloseAudioOut(m_btdrv_handle);
      |         ^~~~~~~~~~~~~~~~~~
/home/matthijs/nx-btred/btred/source/bt_audio_device.cpp: In member function 'void BtAudioDevice::FinalizeBtdrv()':
/home/matthijs/nx-btred/btred/source/bt_audio_device.cpp:129:9: error: 'btdrvStopAudioOut' was not declared in this scope; did you mean 'audoutStopAudioOut'?
  129 |         btdrvStopAudioOut(m_btdrv_handle);
      |         ^~~~~~~~~~~~~~~~~
      |         audoutStopAudioOut
/home/matthijs/nx-btred/btred/source/bt_audio_device.cpp:131:9: error: 'btdrvCloseAudioOut' was not declared in this scope
  131 |         btdrvCloseAudioOut(m_btdrv_handle);
      |         ^~~~~~~~~~~~~~~~~~
/home/matthijs/nx-btred/btred/source/bt_audio_device.cpp:137:5: error: 'btdrvCloseAudioConnection' was not declared in this scope; did you mean 'btdrvCloseHidConnection'?
  137 |     btdrvCloseAudioConnection(m_addr);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
      |     btdrvCloseHidConnection
/home/matthijs/nx-btred/btred/source/bt_audio_device.cpp: In member function 'Result BtAudioDevice::SendAudio(void*)':
/home/matthijs/nx-btred/btred/source/bt_audio_device.cpp:370:10: error: 'btdrvSendAudioData' was not declared in this scope
  370 |     rc = btdrvSendAudioData(m_btdrv_handle, buf, BUF_SIZE, &transferred);
      |          ^~~~~~~~~~~~~~~~~~
/home/matthijs/nx-btred/btred/source/bt_audio_device.cpp: In member function 'void BtAudioDevice::WorkerThread()':
/home/matthijs/nx-btred/btred/source/bt_audio_device.cpp:444:61: error: 'm_btdrv_state' was not declared in this scope
  444 |                 rc = btdrvGetAudioOutState(m_btdrv_handle, &m_btdrv_state);
      |                                                             ^~~~~~~~~~~~~
/home/matthijs/nx-btred/btred/source/bt_audio_device.cpp:444:22: error: 'btdrvGetAudioOutState' was not declared in this scope; did you mean 'audoutGetAudioOutState'?
  444 |                 rc = btdrvGetAudioOutState(m_btdrv_handle, &m_btdrv_state);
      |                      ^~~~~~~~~~~~~~~~~~~~~
      |                      audoutGetAudioOutState
make[1]: *** [/opt/devkitpro/devkitA64/base_rules:14: bt_audio_device.o] Fout 1
make: *** [Makefile:142: build] Fout 2`

If I change the things as make suggests, it suggests another thing, if I do that, it suggests the old thing. I heard there was a pre-compiled version but I was too late.

**Comment by plutooo** [comment]
libnx manually needs this PR: https://github.com/switchbrew/libnx/pull/540


I have uploaded new binaries now, so you don't have to build yourself :)

**Comment by 3DSBricker** [comment]
Thank you!
