### ISSUE TITLE
Pairing Issue

### ISSUE THREAD

**Issue by designgears** [plutooo/nx-btred#7]
On 0.9.2 I was able to pair my headset just fine. 

0.9.3 I get 
Pairing...
Got SSP...

and it hangs there until my headset goes back to sleep.

**Comment by designgears** [comment]
A few reboots and retries and it paired again, very strange. 

---

The sound is still blaring and sounds distorted because of it, the controls seem to be a bit delayed in controlling the sound as well. 

Some minor static in the background with the occasional popping. 

Using Airpods Pro.

---

Some other findings, it seems like when the GPU is being pushed there is a lot more static. I'm comparing the title screen of Monster Hunter Rise to the character creation screen. I turned the background music to 0 in the settings to hear things better.

**Comment by Shan-Mk** [comment]
> A few reboots and retries and it paired again, very strange.
> 
> The sound is still blaring and sounds distorted because of it, the controls seem to be a bit delayed in controlling the sound as well.
> 
> Some minor static in the background with the occasional popping.
> 
> Using Airpods Pro.

hello guys can share ur 0.9.2 files? thank you !!

**Comment by 3DSBricker** [comment]
Whether my GPU is at 921MHz or 307MHz doesn't make a difference with audio, nor does it matter if it is used 100% or 0%. My BT to 3.5MM had the same pairing problem and rebooting indeed helped. I also don't really hear static or noise, it does sound distorted and strange.
