### ISSUE TITLE
No audio 0.9.3

### ISSUE THREAD

**Issue by ajbritain4** [plutooo/nx-btred#8]
Hey, using 0.9.3, 12.0.1, Atmosphere 19.1. Tried some generic Bluetooth headphones, a Bose dock and Airpods and none of them output any audio. Pairs absolutely fine and shuts off the Switch’s audio but that’s it.

After a couple of times waking/sleeping the Switch I got the loud static noise from the Airpods and that’s it.

Tested with Crash 4 and Outer Worlds

thanks

**Comment by chaosrunner** [comment]
Yep I am facing the same issue when trying to connect to bose headphones and google home

0.9.3, atmosphere 19.1, games tested with are Persona 5 strikers, TWEWY and Smash

Edit: using another pair of headphones work with TWEWY and Persona 5 Strikers but not with smash

**Comment by masagrator** [comment]
The same issue with Plantronics Back Beat Pro 2.

Pairing is working. Testing Higurashi and Monster Hunter Rise - no audio in headphones.

0.9.3, 12.0.0, Atmosphere 0.19.1 emummc on Mariko.

**Comment by isotrex** [comment]
The same issue on my end. Tested on all three of my bluetooth TWS - SoundPeats Sonic, Alien Secret QCC010 and Fiil T1 Pro connects. There is no audio. Games tested are Monster Hunter Rise and Borderlands 2.

0.9.3, 12.0.0, Atmosphere 0.19.1 emummc on non-patch system.

**Comment by mhetralla** [comment]
nx-btred 0.9.3
MissionControl 0.5.0 pre-release
Atmosphère 0.19.1, in SysNand
Switch 12.0.1 (Erista)

The Airpods Pro are able to connect, but they only make static noise (only when a sound should be playing in the game). Also, in the btpair application, the name "mhetralla's Airpods Pro" can't be displayed, and "mhetrallaｒçös Airpods Pro" is displayed instead.

The Bose QuietComfort 35 are able to connect for a second, but then they disconnect and the app goes back to "Got SSP...).

**Comment by plutooo** [comment]
I heard updating to 12.0.1 helped a bunch of people, try that

**Comment by masagrator** [comment]
But OP stated that they have 12.0.1...

**Comment by ajbritain4** [comment]
@plutooo Yeah the original issue was for 12.0.1 - I’ve since tried 12.0.0 as well with the exact same result
